In [1]:
import pandas as pd

In [2]:
city_df = pd.read_parquet("../003_data/003_merged-data/merged_cms_ballot-measures_by-city.parquet")

In [5]:
city_vote_df = city_df.dropna(subset=['vote_count'])

,year,county,city,provider_number,profit_or_nonprofit,std_chain_organization,ichcahps_data_availability_code,five_star_data_availability_code,linearized_score_of_rating_of_the_dialysis_facility,five_star,ich_cahps_survey_of_patients_experiences_star_rating,linearized_score_of_rating_of_the_dialysis_center_staff,patient_transplant_waitlist_data_availability_code,standardized_first_kidney_transplant_waitlist_ratio,_of_dialysis_stations,patient_hospital_readmission_category,mortality_rate_facility,vote_type,vote_count
1478,2022,santa clara,san jose,52305,non_profit,independent,1,1,90,4,4,90,1,1.28,25,As Expected,16.6,yes,91918.0
1479,2022,santa clara,san jose,52305,non_profit,independent,1,1,90,4,4,90,1,1.28,25,As Expected,16.6,no,161519.0
1480,2022,orange,orange,52311,non_profit,independent,1,1,93,3,4,91,1,1.32,39,As Expected,20.4,yes,11402.0
1481,2022,orange,orange,52311,non_profit,independent,1,1,93,3,4,91,1,1.32,39,As Expected,20.4,no,30771.0
1482,2022,los angeles,los angeles,52321,non_profit,independent,102,260,None,None,None,None,1,1.1,10,As Expected,None,yes,366958.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6979,2018,kings,hanford,552644,profit,davita,101,260,not Available,,None,not Available,None,None,0,None,15.8,no,10119.0
6980,2018,sacramento,sacramento,52676,non_profit,dialysisclinic,1,1,96,3,None,95,None,None,24,None,15.6,yes,69582.0
6981,2018,sacramento,sacramento,52676,non_profit,dialysisclinic,1,1,96,3,None,95,None,None,24,None,15.6,no,88242.0
6982,2018,orange,orange,50069,non_profit,independent,1,1,91,3,None,89,None,None,39,None,22.7,yes,16240.0
6983,2018,orange,orange,50069,non_profit,independent,1,1,91,3,None,89,None,None,39,None,22.7,no,30642.0